page:

  index: 'Параметры упаковки'
  edit: 'Редактировать параметры упаковки'

breadcrumb:

  index: 'Параметры упаковки продукции'
  edit: 'Редактировать параметры упаковки'


success:
  edit: 'Параметры упаковки успешно обновлены'

danger:
  edit: '%s: Ошибка при обновлении параметров упаковки'

